# Generated by Django 3.1.1 on 2020-09-30 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('medidas', models.CharField(blank=True, max_length=30)),
                ('moneda', models.CharField(choices=[('peso', 'Peso'), ('dolar', 'Dólar'), ('euro', 'Euro'), ('real', 'Real')], default='peso', max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descripcion', models.TextField(blank=True)),
                ('en_venta', models.BooleanField(default=False)),
                ('en_alquiler', models.BooleanField(default=False)),
                ('metros_cubiertos', models.IntegerField(verbose_name='Metros Cubiertos')),
                ('cantidad_habitaciones', models.IntegerField(verbose_name='Cantidad de habitaciones')),
                ('cantidad_banios', models.IntegerField(verbose_name='Cantidad de Baños')),
                ('cantidad_suite', models.IntegerField(verbose_name='Cantidad de Suite')),
                ('servicios', models.ManyToManyField(to='inmueble.Servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
    ]
