# Generated by Django 3.1.1 on 2020-10-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmueble', '0003_auto_20200930_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='inmobiliaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.inmobiliaria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casa',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='inmueble.Servicio'),
        ),
    ]
