# Generated by Django 3.0.10 on 2020-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_migracion_de_servicios_repetidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
