# Generated by Django 3.1.1 on 2020-10-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=90)),
                ('direccion', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(default='Catamarca', max_length=50)),
                ('pais', models.CharField(default='Argentina', max_length=50)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('horario_atencion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmobiliaria',
                'verbose_name_plural': 'Inmobiliarias',
            },
        ),
    ]
