# Generated by Django 3.1.1 on 2020-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='add_field',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
