# Generated by Django 3.1.1 on 2020-10-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_inmobiliaria_add_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmobiliaria',
            name='add_field',
        ),
    ]
